export const canadaSchedules: Record<string, string> = {
  'BOC Business Outlook Survey': 'Trimestriel – 15h30',
  'BOC Financial System Review': 'Mai & Nov. – 15h45',
  'BOC Gov Macklem Speaks': 'Variable',
  'BOC Monetary Policy Report': 'Trimestriel – 15h45',
  'BOC Press Conference': 'Trimestriel – 16h15',
  'BOC Rate Statement': 'BOC – 15h45',
  'BOC Summary of Deliberations': '2 semaines après – 15h45',
  'Beige Book': 'Mercredi (2 semaines avant FOMC) – 20h00',
  'Business Inventories m/m': '2e semaine – 16h00',
  'Capital Spending q/y': 'Trimestriel – 14h30',
  'Capacity Utilization Rate': '3e semaine – 15h15',
  'Challenger Job Cuts y/y': '1er jeudi – 13h30',
  'Company Operating Profits q/q': 'Trimestriel – 14h30',
  'Congressional Elections': 'Nov. (années paires) – non planifié',
  'Corporate Profits q/q': 'Trimestriel – 14h30',
  'Credit Card Spending y/y': 'Mensuel – 14h30',
  'Credit Suisse Economic Expectations': 'Mensuel – variable',
  'Daylight Saving Time Shift': 'Mars & Oct. – non planifié',
  'Economy Watchers Sentiment': '8e – 07h00',
  'Employment Change q/q': 'Trimestriel (avec PIB) – 14h30',
  'Final Employment Change q/q': 'Trimestriel (finale) – 14h30',
  'Fixed Asset Investment ytd/y': '15e – 01h50',
  'Flash Employment Change q/q': 'Trimestriel (flash) – 14h30',
  'Flash GDP q/q': 'Trimestriel (flash) – 14h30',
  'Flash Manufacturing PMI': '23e du mois – 15h45',
  'Flash Services PMI': '23e – 15h45',
  'GDP m/m': '30e – 14h30',
  'GDP q/q': 'Trimestriel – 14h30',
  'GDP q/y': 'Trimestriel – 01h50',
  'Gov Board Member Martin Speaks': 'Variable',
  'Gov Board Member Schlegel Speaks': 'Variable',
  'Gov Board Member Tschudin Speaks': 'Variable',
  'Gov Council Member Gravelle Speaks': 'Variable',
  'Gov Council Member Kozicki Speaks': 'Variable',
  'Gov Council Member Mendes Speaks': 'Variable',
  'Gov Council Member Rogers Speaks': 'Variable',
  'Gov Council Member Vincent Speaks': 'Variable',
  'Bank Lending y/y': '8e – 01h50',
  'Building Permits': '3e semaine – 14h30',
  'Building Permits m/m': '3e semaine – 14h30',
  'BSI Manufacturing Index': 'Variable',
  'Construction PMI': 'Variable',
  'Inflation Expectations q/q': 'Trimestriel – 08h45',
  'Ivey PMI': '5e jour ouvré – 16h00',
  'JST Governor Harada Speaks': 'Variable',
  'Annual Budget Release': 'Variable (Bundeshaushalt)',
  'Autumn Forecast Statement': 'Novembre – variable',
  'Bank Stress Test Results': 'Variable (Fed CCAR)',
}
