export const euroSchedules: Record<string, string> = {
  'Belgian NBB Business Climate': '20e – 15h00',
  'CBI Industrial Order Expectations': '25e – 12h00',
  'CBI Realized Sales': '25e – 12h00',
  'ECB Economic Bulletin': 'Variable – 10h00',
  'ECB Financial Stability Review': 'Mai & Nov. – 10h00',
  'ECB Monetary Policy Meeting Accounts': '4 semaines après – 13h30',
  'ECB President Lagarde Speaks': 'Variable',
  'ECB Press Conference': 'BCE – 14h45',
  'ECB Statement': 'BCE – 13h45',
  'ECOFIN Meetings': 'Mensuel – variable',
  'EU Economic Forecasts': 'Février, Mai, Nov. – 11h00',
  'Euro Summit': 'Variable',
  'Eurogroup Meetings': 'Mensuel – variable',
  'European Parliamentary Elections': 'Juin (tous les 5 ans)',
  'Eurozone CPI m/m': 'Flash : 30e – 11h00',
  'Eurozone CPI y/y': 'Final : 15e – 11h00',
  'Eurozone Composite PMI': 'Flash : 23e – 10h00',
  'Eurozone Core CPI m/m': 'Flash : 30e – 11h00',
  'Eurozone Core CPI y/y': 'Final : 15e – 11h00',
  'Eurozone Employment Change q/q': '45e jour – 11h00',
  'Eurozone GDP q/q': 'Flash : 30e – 11h00',
  'Eurozone GDP y/y': 'Final : 45e jour – 11h00',
  'Eurozone Manufacturing PMI': 'Flash : 23e – 10h00',
  'Eurozone PPI m/m': '1er jour ouvré – 11h00',
  'Eurozone Retail Sales m/m': '1er jour ouvré – 11h00',
  'Eurozone Retail Sales y/y': '1er jour ouvré – 11h00',
  'Eurozone Services PMI': 'Flash : 23e – 10h00',
  'Eurozone Trade Balance': '15e – 11h00',
  'Eurozone Unemployment Rate': '1er jour ouvré – 11h00',
  'FPC Meeting Minutes': 'Variable',
  'FPC Statement': 'Variable',
  'French 10-y Bond Auction': '1er jeudi – 10h50',
  'French Bank Holiday': 'Variable',
  'French Consumer Spending m/m': '30e – 07h30',
  'French Final CPI m/m': '15e – 08h45',
  'French Final Manufacturing PMI': '1er jour ouvré – 09h50',
  'French Final Private Payrolls q/q': 'Trimestriel – 07h30',
  'French Final Services PMI': '5e jour ouvré – 09h50',
  'French Flash GDP q/q': '30e – 07h30',
  'French Flash Manufacturing PMI': '23e – 09h15',
  'French Flash Services PMI': '23e – 09h15',
  'French Gov Budget Balance': 'Trimestriel – 08h45',
  'French Industrial Production m/m': '10e – 08h45',
  'French Parliamentary Elections': 'Juin/Juillet – non planifié',
  'French Prelim CPI m/m': '30e – 08h45',
  'French Prelim GDP q/q': '45e jour – 07h30',
  'French Prelim Private Payrolls q/q': 'Trimestriel – 07h30',
  'French Trade Balance': '7e – 08h45',
  'German 10-y Bond Auction': 'Mercredi – 11h30',
  'German 30-y Bond Auction': 'Variable',
  'German Bank Holiday': 'Variable',
  'German Buba Monthly Report': '15e – 12h00',
  'German Buba President Nagel Speaks': 'Variable',
  'German Factory Orders m/m': '6e – 08h00',
  'German Federal Elections': 'Sept. 2025 – non planifié',
  'German Final CPI m/m': '12e – 14h00',
  'German Final GDP q/q': '45e jour – 08h00',
  'German Final Manufacturing PMI': '1er jour ouvré – 09h30',
  'German Final Services PMI': '4e jour ouvré – 09h30',
  'German Flash Manufacturing PMI': '23e – 09h30',
  'German Flash Services PMI': '23e – 09h30',
  'German GfK Consumer Climate': '27e – 08h00',
  'German Import Prices m/m': '30e – 08h00',
  'German Industrial Production m/m': '7e – 08h00',
  'German PPI m/m': '20e – 08h00',
  'German Prelim CPI m/m': '30e – 14h00',
  'German Prelim GDP q/q': '30e – 08h00',
  'German Retail Sales m/m': '30e – 08h00',
  'German Trade Balance': '8e – 08h00',
  'German Unemployment Change': '1er jour ouvré – 09h55',
  'German WPI m/m': '15e – 08h00',
  'German ZEW Economic Sentiment': '2e mardi – 11h00',
  'German ifo Business Climate': '25e – 10h00',
  'GfK Consumer Confidence': 'Dernier vendredi – 01h01',
  'Italian 10-y Bond Auction': 'Variable – 11h00',
  'Italian Bank Holiday': 'Variable',
  'Italian Industrial Production m/m': '10e – 10h00',
  'Italian Manufacturing PMI': '1er jour ouvré – 09h45',
  'Italian Monthly Unemployment Rate': '30e – 10h00',
  'Italian Prelim CPI m/m': '30e – 11h00',
  'Italian Prelim GDP q/q': '30e – 10h00',
  'Italian Quarterly Unemployment Rate': 'Trimestriel – 10h00',
  'Italian Retail Sales m/m': '7e – 10h00',
  'Italian Services PMI': '5e jour ouvré – 09h45',
  'Italian Trade Balance': '15e – 10h00',
  'Main Refinancing Rate': 'BCE – 13h45',
  'Manufacturing PMI': '1er jour ouvré – 15h45',
  'Monetary Policy Statement': 'BCE – 13h45',
  'Monetary Policy Summary': 'BCE – 13h45',
  'Spanish 10-y Bond Auction': 'Jeudi – 10h30',
  'Spanish Flash CPI y/y': '30e – 09h00',
  'Spanish Flash GDP q/q': '30e – 09h00',
  'Spanish Flash Manufacturing PMI': '23e – 09h15',
  'Spanish Manufacturing PMI': '1er jour ouvré – 09h15',
  'Spanish Services PMI': '5e jour ouvré – 09h15',
  'Spanish Unemployment Change': '1er jour ouvré – 09h00',
  'Spanish Unemployment Rate': 'Trimestriel – 09h00',
}
