export const ukSchedules: Record<string, string> = {
  'BOE Credit Conditions Survey': 'Trimestriel – 12h00',
  'BOE Financial Stability Report': 'Juin & Déc. – 12h00',
  'BOE Gov Bailey Speaks': 'Variable',
  'BOE Inflation Letter': 'Variable',
  'BOE Monetary Policy Report': 'Trimestriel – 12h00',
  'BOE Quarterly Bulletin': 'Trimestriel – 12h00',
  'BRC Retail Sales Monitor y/y': '1er mardi – 01h01',
  'BRC Shop Price Index y/y': '1er mercredi – 01h01',
  'Claimant Count Change': '2e mardi – 08h00',
  'Construction Output m/m': '10e – 08h00',
  'Construction Work Done q/q': '10e – 08h00',
  'Current Account': '8e – 01h50',
  'Halifax HPI m/m': '7e – 09h00',
  'Housing Equity Withdrawal q/q': 'Trimestriel – 08h00',
  'Index of Services 3m/3m': '10e – 08h00',
  'IPPI m/m': '3e mercredi – 08h00',
  'Machine Tool Orders m/m': '10e – 08h00',
  'MPC Member Breeden Speaks': 'Variable',
  'MPC Member Broadbent Speaks': 'Variable',
  'MPC Member Dhingra Speaks': 'Variable',
  'MPC Member Greene Speaks': 'Variable',
  'MPC Member Haskel Speaks': 'Variable',
  'MPC Member Lombardelli Speaks': 'Variable',
  'MPC Member Mann Speaks': 'Variable',
  'MPC Member Pill Speaks': 'Variable',
  'MPC Member Ramsden Speaks': 'Variable',
  'MPC Member Taylor Speaks': 'Variable',
  'MPC Official Bank Rate Votes': 'MPC – 13h00',
  'Net Lending to Individuals m/m': '30e – 10h30',
  'Nationwide CPI y/y': '20e – 01h30',
  'Nationwide HPI m/m': '30e – 08h00',
  'Official Bank Rate': 'MPC – 13h00',
  'Overseas Trade Index q/q': 'Trimestriel – 08h00',
  'Public Sector Net Borrowing': 'Mensuel – 09h00',
  'RICS House Price Balance': '12e – 01h01',
  'RMPI m/m': '1er mercredi – 01h01',
  'RPI y/y': '3e mercredi – 08h00',
  'Rightmove HPI m/m': '15e – 01h01',
  'UK Bank Holiday': 'Variable',
  'UK CPI m/m': '3e mercredi – 08h00',
  'UK CPI y/y': '3e mercredi – 08h00',
  'UK Composite PMI': 'Flash : 23e – 10h30',
  'UK Core CPI y/y': '3e mercredi – 08h00',
  'UK Employment Change q/q': '2e mardi – 08h00',
  'UK GDP q/q': 'Flash : 30e – 08h00',
  'UK GDP y/y': 'Final : 45e jour – 08h00',
  'UK Manufacturing PMI': 'Flash : 23e – 10h30',
  'UK Manufacturing Production m/m': '10e – 08h00',
  'UK NHPI m/m': 'Variable',
  'UK RPI y/y': '3e mercredi – 08h00',
  'UK Retail Sales m/m': '3e vendredi – 08h00',
  'UK Retail Sales y/y': '3e vendredi – 08h00',
  'UK Services PMI': 'Flash : 23e – 10h30',
  'UK Trade Balance': '10e – 08h00',
  'UK Unemployment Rate': '2e mardi – 08h00',
  'UK Wage Growth': '2e mardi – 08h00',
  'Average Earnings Index 3m/y': '2e mardi – 08h00',
}
