export const usSchedules: Record<string, string> = {
  'ADP Non-Farm Employment Change': 'Mercredi (2 jours avant NFP) – 14h15',
  'FOMC Economic Projections': 'FOMC trimestriel – 20h00',
  'FOMC Financial Stability Report': 'Mai & Novembre – 17h00',
  'FOMC Meeting Minutes': '3 semaines après – 20h00',
  'FOMC Member Barkin Speaks': 'Variable',
  'FOMC Member Barr Speaks': 'Variable',
  'FOMC Member Bostic Speaks': 'Variable',
  'FOMC Member Bowman Speaks': 'Variable',
  'FOMC Member Collins Speaks': 'Variable',
  'FOMC Member Cook Speaks': 'Variable',
  'FOMC Member Daly Speaks': 'Variable',
  'FOMC Member Goolsbee Speaks': 'Variable',
  'FOMC Member Hammack Speaks': 'Variable',
  'FOMC Member Harker Speaks': 'Variable',
  'FOMC Member Jefferson Speaks': 'Variable',
  'FOMC Member Kashkari Speaks': 'Variable',
  'FOMC Member Kugler Speaks': 'Variable',
  'FOMC Member Logan Speaks': 'Variable',
  'FOMC Member Mester Speaks': 'Variable',
  'FOMC Member Miran Speaks': 'Variable',
  'FOMC Member Musalem Speaks': 'Variable',
  'FOMC Member Paulson Speaks': 'Variable',
  'FOMC Member Schmid Speaks': 'Variable',
  'FOMC Member Waller Speaks': 'Variable',
  'FOMC Member Williams Speaks': 'Variable',
  'FOMC Press Conference': 'FOMC – 20h30',
  'FOMC Statement': 'FOMC – 20h00',
  'Fed Chair Powell Speaks': 'Variable',
  'Fed Chair Powell Testifies': 'Variable',
  'Fed Monetary Policy Report': 'Février & Juillet – 17h00',
  'Federal Budget Balance': '15e – 20h00',
  'Federal Election': 'Non applicable',
  'Federal Funds Rate': 'FOMC – 20h00',
  'Initial Jobless Claims': 'Jeudi – 14h30',
  'Advance GDP Price Index q/q': 'Trimestriel – 14h30',
  'Advance GDP q/q': 'Trimestriel – 14h30',
  'Average Hourly Earnings m/m': '1er vendredi – 14h30',
  'CB Consumer Confidence': 'Dernier mardi – 16h00',
  'CB Leading Index m/m': '3e semaine – 16h00',
  'Case-Shiller Home Price Index': '4e mardi – 15h00',
  'CPI Flash Estimate y/y': 'Variable – 14h30',
  'CPI m/m': '2e semaine – 14h30',
  'CPI q/q': 'Trimestriel (avec PIB) – 14h30',
  'CPI y/y': '2e semaine – 14h30',
  'Chicago PMI': 'Dernier jour ouvré – 15h45',
  'Cleveland Fed Inflation Expectations': '10e – 16h00',
  'Construction Spending m/m': '1er jour ouvré – 16h00',
  'Consumer Confidence': 'Dernier mardi – 16h00',
  'Consumer Credit m/m': '30e – 03h00',
  'Consumer Inflation Expectations': 'Trimestriel – 14h30',
  'Core CPI Flash Estimate y/y': 'Variable – 14h30',
  'Core CPI m/m': '2e semaine – 14h30',
  'Core CPI y/y': '2e semaine – 14h30',
  'Core Durable Goods Orders m/m': '4e semaine – 14h30',
  'Core PCE Price Index m/m': '4e semaine – 14h30',
  'Core PPI m/m': '2e semaine – 14h30',
  'Core Retail Sales m/m': '2e semaine – 14h30',
  'Core Retail Sales q/q': '2e semaine – 14h30',
  'Crude Oil Inventories': 'Mercredi – 16h30',
  'Durable Goods Orders m/m': '4e semaine – 14h30',
  'Empire State Manufacturing Index': '15e – 14h30',
  'Employment Change': '1er vendredi – 14h30',
  'Employment Change q/q': 'Trimestriel (avec PIB) – 14h30',
  'Employment Cost Index q/q': 'Dernier mardi du mois – 14h30',
  'Existing Home Sales': '3e semaine – 16h00',
  'Factory Orders m/m': '1ère semaine – 16h00',
  'Final CPI y/y': '2e semaine – 14h30',
  'Final Core CPI y/y': '2e semaine – 14h30',
  'Final Employment Change q/q': 'Trimestriel (finale) – 14h30',
  'Final GDP Price Index q/q': 'Trimestriel (finale) – 14h30',
  'Final GDP Price Index y/y': 'Trimestriel (finale) – 14h30',
  'Final GDP q/q': 'Trimestriel (finale) – 14h30',
  'Final Manufacturing PMI': '3e jour ouvré – 15h45',
  'Final Services PMI': '5e jour ouvré – 15h45',
  'Final Wholesale Inventories m/m': '2e semaine – 16h00',
  'Goods Trade Balance': '4e semaine – 14h30',
  'HPI m/m': '4e mardi – 15h00',
  'HPI y/y': '4e mardi – 15h00',
  'Household Spending m/m': '4e semaine – 14h30',
  'Household Spending y/y': '4e semaine – 14h30',
  'Housing Starts': '3e semaine – 14h30',
  'Housing Starts y/y': '3e semaine – 14h30',
  'ISM Manufacturing PMI': '1er jour ouvré – 16h00',
  'ISM Manufacturing Prices': '1er jour ouvré – 16h00',
  'ISM Services PMI': '3e jour ouvré – 16h00',
  'Import Prices m/m': '2e semaine – 14h30',
  'Import Prices q/q': '2e semaine – 14h30',
  'Industrial Production m/m': '3e semaine – 15h15',
  'Industrial Production y/y': '3e semaine – 15h15',
  'JOLTS Job Openings': 'Mardi (1er semaine) – 16h00',
  'Jackson Hole Symposium': 'Août – variable',
  'Labor Cost Index q/q': 'Trimestriel – 14h30',
  'Labor Productivity q/q': '1ère semaine – 14h30',
  'Leading Indicators': '3e semaine – 16h00',
  'Median CPI y/y': '2e semaine – 14h30',
  'MI Inflation Expectations': '2e/4e vendredi – 16h00',
  'MI Inflation Gauge m/m': '2e/4e vendredi – 16h00',
  'MI Leading Index m/m': '2e/4e vendredi – 16h00',
  'NFIB Small Business Index': '2e mardi – 12h00',
  'Non-Farm Employment Change': '1er vendredi du mois – 14h30',
  'Non-Manufacturing PMI': '3e jour ouvré – 15h45',
  'New Home Prices m/m': '4e semaine – 16h00',
  'New Home Sales': '4e semaine – 16h00',
  'NAHB Housing Market Index': '3e semaine – 16h00',
  'Pending Home Sales m/m': '4e semaine – 16h00',
  'Personal Income m/m': '4e semaine – 14h30',
  'Personal Spending m/m': '4e semaine – 14h30',
  'Philly Fed Manufacturing Index': '3e jeudi – 14h30',
  'Prelim Business Investment q/q': 'Trimestriel – 14h30',
  'Prelim Flash GDP q/q': 'Trimestriel – 14h30',
  'Prelim GDP Price Index q/q': 'Trimestriel – 14h30',
  'Prelim GDP Price Index y/y': 'Trimestriel – 14h30',
  'Prelim GDP q/q': 'Trimestriel – 14h30',
  'Prelim Industrial Production m/m': '3e semaine – 15h15',
  'Prelim Nonfarm Productivity q/q': '1ère semaine – 14h30',
  'Prelim Unit Labor Costs q/q': '1ère semaine – 14h30',
  'Prelim UoM Consumer Sentiment': '2e vendredi – 16h00',
  'Prelim UoM Inflation Expectations': '2e vendredi – 16h00',
  'Prelim Wholesale Inventories m/m': '2e semaine – 16h00',
  'President Biden Speaks': 'Variable',
  'President Trump Speaks': 'Variable',
  'Presidential Election': 'Nov. 2028 – non planifié',
  'PPI Input m/m': '2e semaine – 14h30',
  'PPI Input q/q': '2e semaine – 14h30',
  'PPI Output m/m': '2e semaine – 14h30',
  'PPI Output q/q': '2e semaine – 14h30',
  'PPI m/m': '2e semaine – 14h30',
  'PPI q/q': '2e semaine – 14h30',
  'PPI y/y': '2e semaine – 14h30',
  'RCM/TIPP Economic Optimism': '2e semaine – 16h00',
  'Retail Sales m/m': '2e semaine – 14h30',
  'Retail Sales q/q': '2e semaine – 14h30',
  'Retail Sales y/y': '2e semaine – 14h30',
  'Revised Business Investment q/q': 'Trimestriel – 14h30',
  'Revised GDP q/q': 'Trimestriel – 14h30',
  'Revised Industrial Production m/m': '3e semaine – 15h15',
  'Revised Nonfarm Productivity q/q': '1ère semaine – 14h30',
  'Revised Unit Labor Costs q/q': '1ère semaine – 14h30',
  'Revised UoM Consumer Sentiment': '4e vendredi – 16h00',
  'Revised UoM Inflation Expectations': '4e vendredi – 16h00',
  'Richmond Manufacturing Index': '4e mardi – 16h00',
  'Trade Balance': '1ère semaine – 14h30',
  'Treasury Currency Report': 'Avril & Octobre – 22h00',
  'Treasury Sec Yellen Speaks': 'Variable',
  'Trimmed CPI y/y': '2e semaine – 14h30',
  'Trimmed Mean CPI q/q': '2e semaine – 14h30',
  'Unemployment Claims': 'Jeudi – 14h30',
  'Unemployment Rate': '1er vendredi – 14h30',
  'USD-Denominated Trade Balance': '1ère semaine – 14h30',
  'Wholesale Inventories m/m': '2e semaine – 16h00',
  'Wholesale Sales m/m': '2e semaine – 16h00',
}
